project_id = "nxissybzirfxjewvamgy"

[functions.asaas-cobranca]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.gerar-mensalidades-automaticas]
verify_jwt = false

[functions.gerar-fatura-sistema]
verify_jwt = false
