project_id = "nxissybzirfxjewvamgy"

[functions.asaas-cobranca]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.gerar-mensalidades-automaticas]
verify_jwt = false

[functions.gerar-fatura-sistema]
verify_jwt = false

[functions.enviar-link-pagamento]
verify_jwt = true

[functions.setup-arena-admin]
verify_jwt = false

[functions.notificar-agendamentos-proximos]
verify_jwt = false

[functions.enviar-whatsapp-evolution]
verify_jwt = true

[functions.verificar-vencimentos-arena]
verify_jwt = false

[functions.lembretes-pagamento]
verify_jwt = false
