// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxissybzirfxjewvamgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54aXNzeWJ6aXJmeGpld3ZhbWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTk0NzIsImV4cCI6MjA3NDY3NTQ3Mn0.X4Hn_e5Cm46-8LyKuiNEQx_h3Y3MKHVmY8_LfpPBo54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});